# docker run --hostname my-rabbit -p 5672:5672 -p 15672:15672 --name some-rabbit rabbitmq:3.8
version: "3"
services:
  broker:
    build:
      context: .
      dockerfile: ./dockerfiles/broker.dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
  producer:
    depends_on:
      - broker
    build:
      context: .
      dockerfile: ./dockerfiles/producer.dockerfile
    ports:
      - "3000:3000"
    command: ["./wait-rabbitmq.sh", "broker:15672", "./main"]
  consumer:
    depends_on:
      - producer
    build:
      context: .
      dockerfile: ./dockerfiles/consumer.dockerfile
    command: ["./wait-rabbitmq.sh", "broker:15672", "./main"]
