version: "3"
services:
  broker:
    build:
      context: .
      dockerfile: ./dockerfiles/broker.dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
  database:
    image: redis:5.0-alpine
    ports:
      - "6379:6379"
  producer:
    depends_on:
      - broker
    build:
      context: .
      dockerfile: ./dockerfiles/producer.dockerfile
    ports:
      - "3000:3000"
    command: ["./wait-rabbitmq.sh", "broker:15672", "./main"]
  consumer:
    depends_on:
      - database
      - producer
    build:
      context: .
      dockerfile: ./dockerfiles/consumer.dockerfile
    command: ["./wait-rabbitmq.sh", "broker:15672", "./main"]
